### ISSUE TITLE
Get followers

### ISSUE THREAD

**Issue by enderahmetyurt** [enderahmetyurt/gistcatch#1]

**Comment by shivanibhanwal** [comment]
I will pick this @enderahmetyurt do you need to add me in the collaborator?

**Comment by shivanibhanwal** [comment]
I have some suggestions too @enderahmetyurt 
- Readme file should be updated which give more idea about project and setup
- UI Improvements for the dashboard.
- Some naming convention  changes as per best practices

**Comment by enderahmetyurt** [comment]
Actually #6 solve that issue.

**Comment by shivanibhanwal** [comment]
@enderahmetyurt I have made UI changes but looks like you have closed the Issue. Do you want to open a new issue for the UI improvements??
Screenshot of my change
<img width="546" alt="screen shot 2018-10-15 at 7 00 40 pm" src="https://user-images.githubusercontent.com/1167588/46954237-b2a6de00-d0ad-11e8-82b3-a2c38d399896.png">

**Comment by enderahmetyurt** [comment]
@shivanibhanwal it looks good thank you 🙏 Yes please open a new issue and pr and let's talk on there :)
