### ISSUE TITLE
Beautify Gists List page

### ISSUE THREAD

**Issue by shivanibhanwal** [enderahmetyurt/gistcatch#12]

**Comment by shivanibhanwal** [comment]
@enderahmetyurt  I have created another PR with the style changes for the ListView and back button moved to the top. This is how it looks

![Uploading Screen Shot 2018-10-16 at 8.54.09 AM.png…]()

**Comment by enderahmetyurt** [comment]
thanks @shivanibhanwal. Listview should be good but I am thinking this issue https://github.com/enderahmetyurt/gistcatch/issues/4 for a gist preview. Can you handle it?

**Comment by shivanibhanwal** [comment]
Yes @enderahmetyurt I have planned, already started with that I think by tomorrow I should be able to do that. My assumption is to just get the gist content and display in the content section on click of list view.
--
