### ISSUE TITLE
Star/unstar a gist

### ISSUE THREAD

**Issue by enderahmetyurt** [enderahmetyurt/gistcatch#16]
The user should star or unstar a gist from developer's gists page.

**Comment by shivanibhanwal** [comment]
@enderahmetyurt There are various possibilities, what you are thinking to do??
- Show Star in our gist list which is the stared gist 
- Star the GitHub -gist from this app
- Locally implement the star for the gist

**Comment by enderahmetyurt** [comment]
- No, I don't think to separate star list for now. I want to show a star icon in Gist name line. If the gist was stared before the star icon should be bold.
- Just staring a gist from the app.

My point is here that I want to star and unstar a Gist from the app. And I want to see that I stared or not the Gist that I look on the app.

Am I clear?
