### ISSUE TITLE
Show following and followers on dashboard

### ISSUE THREAD

**Issue by enderahmetyurt** [enderahmetyurt/gistcatch#2]
following and followers show on tabs

**Comment by luizpicolo** [comment]
Follow and followers for the current user or the list of users?

**Comment by enderahmetyurt** [comment]
For current user. As you see when you authenticate with Github application you can see your followings on the dashboard. We need to add current user's followers

**Comment by cesargralmeida** [comment]
Hey, could i tackle this one? :-)

**Comment by enderahmetyurt** [comment]
yes you can :)

**Comment by enderahmetyurt** [comment]
thanks @cesargralmeida
