### ISSUE TITLE
Image Gists cannot be opened

### ISSUE THREAD

**Issue by enderahmetyurt** [enderahmetyurt/gistcatch#28]
If there is an image in a Gist, it cannot render the gif. It tries to render as a html file. @shivanibhanwal could you look it?

**Comment by shivanibhanwal** [comment]
Sure @enderahmetyurt I will check as soon as i get time

**Comment by shivanibhanwal** [comment]
@filipewl  all looks good we can go ahead with this.
@enderahmetyurt everything looks good shall I merge the PR?

**Comment by enderahmetyurt** [comment]
@shivanibhanwal you can but not now. After checking and merging @filipewl PRs about creating and listint Gists
