### ISSUE TITLE
Unnecessary alert

### ISSUE THREAD

**Issue by enderahmetyurt** [enderahmetyurt/gistcatch#34]
Hi,
@filipewl This is a bug when I already signed. I just visited http://www.gistcatch.com/dashboard

![gc_error](https://user-images.githubusercontent.com/447588/47837218-3a822d00-ddbc-11e8-9c43-45a0b66e5b91.PNG)

Could you look it?

**Comment by filipewl** [comment]
I can, @enderahmetyurt!

**Comment by filipewl** [comment]
@enderahmetyurt, you can tell the exact steps you took to reproduce the issue? Was there anything particular? I just signed in both locally and in https://www.gistcatch.com and the flash message wasn't displayed.

I know this message is related to [Devise's "unauthorization"](https://github.com/plataformatec/devise/blob/715192a7709a4c02127afb067e66230061b82cf2/config/locales/en.yml#L17), but I'm not sure how it's showing up at the `/dashboard` route. 
😕

**Comment by enderahmetyurt** [comment]
Sorry @filipewl I cannot too reproduce the error. After I while when I visit the  https://www.gistcatch.com/dashboard, error appears. Maybe we can just pass over.
