### ISSUE TITLE
Collecting error alerts 

### ISSUE THREAD

**Issue by enderahmetyurt** [enderahmetyurt/gistcatch#35]
@filipewl New form error messages should collect header of the form. This view is not true. Could you fix it?

![gc_alerts_bug](https://user-images.githubusercontent.com/447588/47839958-b16ff380-ddc5-11e8-8dc3-b52ce2846179.PNG)

**Comment by filipewl** [comment]
Yeah, I can do it!

**Comment by enderahmetyurt** [comment]
@filipewl have you did anything about it?

**Comment by filipewl** [comment]
@enderahmetyurt, check https://github.com/enderahmetyurt/gistcatch/pull/37.

By the way, I just noticed, while looking at https://gist.github.com/, we don't need a presence validation for the description field. Only the file's content that can't be blank.

![i9uxlidlcf](https://user-images.githubusercontent.com/381395/47953011-2f630480-df56-11e8-905e-506fa4ef6dfc.gif)

Shall I remove our current description presence validation?
https://github.com/enderahmetyurt/gistcatch/blob/e47192cf3f95a0d786019c5d1069cef3fe0c40b5/app/models/gist.rb#L14
